[package]
name = "rbal"
version = "0.1.0"
edition = "2024"

[profile.release]
strip = true

[dependencies]
chrono = "0.4.40"
clap = { version = "4.5.32", features = ["derive"] }
dirs = "6.0.0"
dotenv = "0.15.0"
rusqlite = { version = "0.34.0", features = ["bundled", "csvtab", "vtab"] }
